# Generated by Django 5.2.1 on 2025-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("MILE", "One Mile Run"),
                            ("INTERVAL", "Interval Training"),
                            ("LONG", "Long Distance"),
                            ("OTHER", "Other"),
                        ],
                        default="MILE",
                        max_length=20,
                    ),
                ),
                ("distance_km", models.FloatField(help_text="Distance in kilometers")),
                (
                    "duration_minutes",
                    models.FloatField(help_text="Duration in minutes"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of the run"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional comments", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
