# Generated by Django 5.2.1 on 2025-05-13 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.FloatField(help_text="Weight in kilograms")),
                (
                    "body_fat_percentage",
                    models.FloatField(
                        blank=True, help_text="Optional body fat percentage", null=True
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of measurement"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weight Entries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="weight_weig_user_id_de1410_idx"
                    )
                ],
            },
        ),
    ]
